/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/template/AppFooter.vue')['default']
    AppHeader: typeof import('./components/template/AppHeader.vue')['default']
    Header: typeof import('./components/template/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HotelFilter: typeof import('./components/Hotel/HotelFilter.vue')['default']
    HotelList: typeof import('./components/Hotel/HotelList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
