/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/template/AppFooter.vue')['default']
    AppHeader: typeof import('./components/template/AppHeader.vue')['default']
    AppNotification: typeof import('./components/AppNotification.vue')['default']
    CurrencyInput: typeof import('./components/CurrencyInput.vue')['default']
    HotelDetail: typeof import('./components/HotelDetail.vue')['default']
    HotelFilter: typeof import('./components/HotelHome/HotelFilter.vue')['default']
    HotelList: typeof import('./components/HotelHome/HotelList.vue')['default']
    HotelModalDetail: typeof import('./components/HotelHome/HotelModalDetail.vue')['default']
    HotelSort: typeof import('./components/HotelHome/HotelSort.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
