/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/HotelComparation': RouteRecordInfo<'/HotelComparation', '/HotelComparation', Record<never, never>, Record<never, never>>,
    '/HotelReservation/': RouteRecordInfo<'/HotelReservation/', '/HotelReservation', Record<never, never>, Record<never, never>>,
    '/HotelReservation/HotelReservationSelected': RouteRecordInfo<'/HotelReservation/HotelReservationSelected', '/HotelReservation/HotelReservationSelected', Record<never, never>, Record<never, never>>,
    '/HotelReservation/HotelReservationSummary': RouteRecordInfo<'/HotelReservation/HotelReservationSummary', '/HotelReservation/HotelReservationSummary', Record<never, never>, Record<never, never>>,
    '/HotelReservation/HotelReservationUser': RouteRecordInfo<'/HotelReservation/HotelReservationUser', '/HotelReservation/HotelReservationUser', Record<never, never>, Record<never, never>>,
  }
}
